Repository stolostron/cluster-templates-operator, pull requests merged in 2023-02, with the labels that each got.

#87 Report error in case of helchart client failure
  api/v1alpha1/clustertemplate_types.go
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/clustertemplate.openshift.io_clustertemplates.yaml
  config/crd/bases/clustertemplate.openshift.io_clustertemplates.yaml
  controllers/clustertemplate_controller.go
  controllers/clustertemplate_controller_test.go
  go.mod
  go.sum
Labels: approved, lgtm, needs-ok-to-test

#92 Add creation of argocd namespace to doc
  docs/quick-start.md
Labels: approved, lgtm

#100 Update readme
  README.md
Labels: approved

#101 Fix Readme
  README.md
Labels: approved

#102 Add COMPONENT_VERSION file to resolve publish issues
  COMPONENT_NAME
Labels: approved, lgtm

#98 Return only helm with secret helm defined
  bridge/router.go
  bridge/router_test.go
Labels: approved, lgtm

#93 Add nodeport address value
  hypershift-kubevirt-template-0.0.1.tgz
  hypershift-kubevirt-template-0.0.2.tgz
  hypershift-kubevirt-template/Chart.yaml
  hypershift-kubevirt-template/templates/hostedcluster.yaml
  hypershift-kubevirt-template/values.schema.json
  hypershift-kubevirt-template/values.yaml
  hypershift-template-0.0.2.tgz
  hypershift-template-0.0.3.tgz
  hypershift-template/Chart.yaml
  hypershift-template/templates/hostedcluster.yaml
  hypershift-template/values.schema.json
  hypershift-template/values.yaml
  index.yaml
Labels: lgtm

#103 Add Ondra to approvers/reviewers
  OWNERS
Labels: approved

#91 Add support for basic auth in helm
  bridge/router.go
  helm/chart.go
  helm/chart_test.go
  helm/client.go
  helm/repo.go
  testutils/helm/server.go
Labels: approved, lgtm

#96 Create ManagedCluster & import when creating CTI
  Dockerfile
  api/v1alpha1/clustertemplateinstance_conditions.go
  api/v1alpha1/clustertemplateinstance_conditions_test.go
  api/v1alpha1/clustertemplateinstance_types.go
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/cluster-aas-operator.clusterserviceversion.yaml
  bundle/manifests/clustertemplate.openshift.io_clustertemplateinstances.yaml
  clustersetup/clustersetup.go
  clustersetup/clustersetup_test.go
  config/crd/bases/clustertemplate.openshift.io_clustertemplateinstances.yaml
  config/rbac/role.yaml
  controllers/claas_controller.go
  controllers/claas_controller_test.go
  controllers/clustertemplateinstance_controller.go
  controllers/clustertemplateinstance_controller_test.go
  controllers/suite_test.go
  go.mod
  go.sum
  main.go
  ocm/managedcluster.go
  ocm/managedcluster_test.go
  ocm/suite_test.go
  testutils/testcrds/optional/ocm/managedcluster_crd.yaml
  utils/resource.go
  utils/resource_test.go
  utils/suite_test.go
Labels: approved, lgtm

#104 Add git route to bridge server
  Dockerfile
  bridge/router.go
  bridge/router_test.go
  controllers/clustertemplate_controller.go
  controllers/defaultresources/hypershifttemplate_controller.go
  controllers/suite_test.go
  go.mod
  main.go
  repository/chart.go
  repository/chart_test.go
  repository/client.go
  repository/client_test.go
  repository/git.go
  repository/git_test.go
  repository/repo.go
  repository/suite_test.go
  testutils/git/base
  testutils/helm/server.go
Labels: approved, lgtm
